version: '3.7'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "5000:5000"
        volumes:
            - ./docker/dev/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/dev/nginx/auth/htpasswd:/etc/nginx/auth/htpasswd
        depends_on:
            - registry
    # контейнер для реестров
    registry:
        image: registry:2
        volumes:
            - registry:/var/lib/registry

volumes:
    registry: